-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(p.PRICE * o.sales_amount) as SALES
from PRODUCT p join OFFLINE_SALE o on p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC